service: default
runtime: custom
env: flex
instance_class: F2
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
env_variables:
  PYTHONPATH: "/app"
liveness_check:
  path: "/health"
  port: 8080
readiness_check:
  path: "/readiness"
  port: 8080
