name: Deploy App Engine

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # This is required to get the OIDC token
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/354181841885/locations/global/workloadIdentityPools/githubdeploy/providers/Github'
          service_account: 'app-engine-deployer@ff-scheduler-466320.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: app.yaml
